language: go

addons:
  apt:
    packages:
      - gcc-multilib
      - libc6-i386

cache:
  directories:
    - $HOME/tools

install:
  - go get mynewt.apache.org/newt/newt
  - newt install

before_script:
  - ./install_gcc-arm-none-eabi.sh
  - export PATH=$HOME/tools/bin:$PATH

script:
  - newt test all --exclude net/oic
  - newt build arduino_testbench
