language: go

addons:
  apt:
    packages:
    - gcc-multilib
    - libc6-i386

cache:
  directories:
  - $HOME/tools

install:
- ./install_gcc-arm-none-eabi.sh
- ./install_runtime.sh

script:
- ./build.sh $TARGET

env:
  matrix:
  - TARGET=arduino
  - TARGET=nrf52
  global:
  - secure: uG37+MTW2z2k+vcPIe/eas4TymwWTJYypykg+KEr2FSXJ2T2ThqDJEf7AP/R9uUPcyMTQ3nxqij2fXZ0Ayetr6ytXhBAofm2U/6QnwB8Q/xgkSd2T0LioNXNCNbfnkB32J/ugk7YVaSEDRQudfm4NAZP/nF8jsgbuWVwqTNj35028ceK01EVY37wIVqIdTdijED8ljgMWEy1UC8M7L8TNsAeq0Eh36EecWBQzKkX8WrekuPKwsbv6BerfnYLzrCwtn0q8Hq8PlVhC3eGb9U/7u8q+70jWtEvkyU44hv/vxJimOOR8sGfwkK95zow0o++VeJksuvSHkIpE2v9VU85aFhYxm/M5xYG/jG0XO/KgT+7PAGZDsyTwfHhculG592V9u6K1bVCn6m8bF+VBrZvIJOK/uHCnBwTLfPAX9astgX0sXyjDTGiDGw1aHxx9o+HQC+I9AfHt17UqD0oSJKeXSaoARPjIJZSxFNLvkunQOznTevgVT1DagxxClwjtU1IkEFVR86ZxQr2cYHbEUwH8/QzpCd598+ZVwowIGZ/4dmhNmrwi/YKlJJEHBlgO86+2dvfG7kBiBFixENlnKxj1vHbTyTcJBL2ilC55uZGtKgybH71HFso9BaNub4rpBTffR6QVptBbyFWDMEvtlEA6EzcCkD2grX9QxQNnsasZlE=
  - secure: jjvbUixSUyGqUDS06jSEpEFrHM9NCVRRsWS9A/ElAsgmpyi3YjkOVktzTEoyOv+erHL9SZ7mYO6fDNWyD7bRUVzaEIjuvdwlSS7x2JjbfYzIXgKmfxhFTdajyQpukMIO43g05q5nejNoR7Kbvh41basWN2CcR1RGEg3P0Pr69q05RUvIs/uUApMdK7KOxlQW9RAWmqR5kYdnmxairw/XfZUC+tXK8O79DIBM0464OpaMm8JQe2xGFdgKquYHov15B+y5k7qJhQzOvK/Vc+ubfRJ3ZSIaZ4OkVnX9XbmuTo3TqYWEfxP9XuyCXVFlKOvuiYXX5wCPcn6n/bVVkiHVXSIWA9fQ22xHc36J4H2xebdjaRacAV6FaybPjj2X4y/F7Hjol+elpG6ZOx5MfjxigL3wZCQt98nh1DjxXbaFZUa467esJs47VbkDEsqBhoQNv4+cLhGW2LLAFKJi79lljGd0hh4Gpi0u+RyXUG7YWBpzjZvZk3+5mLGB+6SS2yJR1l1rs3SZjT0wM44sd14KEAhSfeyqrmCX4ej+Ak0F/KbabE6yV6VlfdTnhWet/cJE8GbrbQwUUp9+gGEmtTqzWP24jzzFw7vpTlk3/6OXUD5z89R6GPYjhxTo0MtpeQBX8kMNfg2tKTjL4qcKU0JLuQfKxNFKxX+7L5lGzoBm84c=
